# Generated by Django 3.2.7 on 2021-10-13 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20211013_2129'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskDateTime',
            new_name='TaskDate',
        ),
    ]
