# Generated by Django 3.2.7 on 2021-10-16 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_task_complete'),
    ]

    operations = [
        migrations.CreateModel(
            name='threads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskTitle', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.threads'),
        ),
    ]
