# Generated by Django 3.2.7 on 2021-10-16 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20211016_2311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='threads',
            old_name='taskTitle',
            new_name='Title',
        ),
    ]
