# Generated by Django 3.2.7 on 2021-10-13 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_taskdatetime_taskdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskDate',
        ),
        migrations.DeleteModel(
            name='TaskDesc',
        ),
    ]
